version: '3.8'

services:

  mongo:
    image: mongo:latest
    container_name: mongo_database
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: lappis
    volumes :
      - dataBase_mongo:/data/mongo

  app:
    container_name: py_container
    image: python:3.8
    build: .
    command: python src/main.py
    command: tail -f /dev/null
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  
volumes :
  dataBase_mongo :
    driver : local